name: Concurrency Demo

on: 
    workflow_dispatch:

concurrency:
    group: production
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest

    
        steps:
        - name: Simulate deployment
          run: |
            echo "Deployment started"
            sleep 60
            echo "Deployment completed"

