name: Reusable test workflow
 
on:
    workflow_call:
        inputs:
            app_name:
                required: true
                type: string

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Hello
              run: echo "Running reusable workflow"

            - run: echo "App = ${{ inputs.app_name }}"