name: Reusable test workflow
 
on:
    workflow_call:
        secrets:
            demo_secret:
                required: true

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Hello
              run: echo "Running reusable workflow"

            - run: echo "${{ secrets.demo_secret}}"